#!/usr/bin/python

# Copyright 2011 Jeff Mendoza <jefflmendoza@gmail.com>
#
# This file is part of Plain MAME Frontend.
#
# Plain MAME Frontend is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Plain MAME Frontend is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Plain MAME Frontend.  If not, see <http://www.gnu.org/licenses/>.

import sys
import os
import cProfile

python_dir=os.path.join(os.path.dirname(os.path.realpath(sys.argv[0])),"..")
sys.path.append(python_dir)

import plain_mame_frontend.core

def foo():
    plain_mame_frontend.core.Core().get_game_list()

cProfile.run('foo()', 'pmfeprof')

import pstats
p = pstats.Stats('pmfeprof')
p.strip_dirs()

p.sort_stats('cumulative').print_stats(10)
print "------------------"
p.sort_stats('time').print_stats(10)
