#!/usr/bin/python

# Copyright 2011 Jeff Mendoza <jefflmendoza@gmail.com>
#
# This file is part of Plain MAME Frontend.
#
# Plain MAME Frontend is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Plain MAME Frontend is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Plain MAME Frontend.  If not, see <http://www.gnu.org/licenses/>.

import sys
import os

PKGDATADIR="/usr/share/plain-mame-frontend"
extra_python_dir=""
#PKGDATADIR=os.path.join(os.path.dirname(os.path.realpath(sys.argv[0])),"..",
#                        "datadir")
#extra_python_dir=os.path.join(os.path.dirname(os.path.realpath(sys.argv[0])),
#                              "..")

sys.path.extend([PKGDATADIR, extra_python_dir])

import pmfe_cli
pmfe_cli.main(sys.argv[1:])
